"""Contextual Notion search — uses Claude to understand the PR, then searches semantically."""

from __future__ import annotations

from pr_review_agent.models.notion import NotionContext, NotionSearchResult
from pr_review_agent.notion.client import NotionMCPClient
from pr_review_agent.notion.relevance import extract_relevant_sections


async def contextual_search(
    client: NotionMCPClient,
    pr_summary: str,
    max_results: int = 5,
) -> list[NotionSearchResult]:
    """Search Notion for pages relevant to the PR.

    Uses the PR summary (generated by Claude) as the search query.
    This is contextual — we search for the *intent*, not just keywords.
    """
    # Search using the PR summary as a contextual query
    raw_results = await client.search_pages(pr_summary)

    results: list[NotionSearchResult] = []
    for item in raw_results[:max_results]:
        page_id = _extract_page_id(item)
        title = _extract_title(item)
        url = _extract_url(item)

        # Fetch full page content for relevance scoring
        content = ""
        if page_id:
            try:
                content = await client.get_page_content(page_id)
            except Exception:
                content = str(item.get("content", ""))

        results.append(NotionSearchResult(
            page_id=page_id,
            title=title,
            url=url,
            content=content,
        ))

    return results


async def fetch_page_by_url(client: NotionMCPClient, url: str) -> NotionSearchResult:
    """Fetch a specific Notion page by URL."""
    # Extract page ID from URL
    page_id = _page_id_from_url(url)

    content = await client.get_page_content(page_id)

    return NotionSearchResult(
        page_id=page_id,
        title=f"Page {page_id[:8]}...",
        url=url,
        content=content,
    )


async def fetch_supplementary_context(
    client: NotionMCPClient,
    page_urls: list[str],
    pr_summary: str,
    model: str = "claude-haiku-4-5-20251001",
) -> list[NotionContext]:
    """Fetch pre-configured supplementary pages and extract relevant sections.

    For each URL, fetches the page content, then uses Haiku to extract
    only the sections relevant to the PR. Pages with no relevant content
    are skipped.
    """
    contexts: list[NotionContext] = []
    for url in page_urls:
        try:
            page_id = _page_id_from_url(url)
            content = await client.get_page_content(page_id)

            extracted = extract_relevant_sections(
                pr_summary=pr_summary,
                page_content=content,
                page_title=f"Page {page_id[:8]}...",
                model=model,
            )
            if extracted:
                contexts.append(NotionContext(
                    page_id=page_id,
                    page_url=url,
                    title=f"Page {page_id[:8]}...",
                    description="Supplementary context page",
                    raw_content=extracted,
                ))
        except Exception:
            # Skip pages that fail to fetch
            continue
    return contexts


def _extract_page_id(item: dict) -> str:
    """Extract page ID from a Notion search result."""
    return item.get("id", item.get("page_id", ""))


def _extract_title(item: dict) -> str:
    """Extract title from a Notion search result."""
    # Try common Notion response formats
    if "properties" in item:
        props = item["properties"]
        for key in ("Name", "Title", "title", "name"):
            if key in props:
                prop = props[key]
                if isinstance(prop, dict) and "title" in prop:
                    titles = prop["title"]
                    if isinstance(titles, list) and titles:
                        first = titles[0]
                        return (
                            first.get("plain_text", "")
                            or first.get("text", {}).get("content", "")
                        )
                elif isinstance(prop, str):
                    return prop

    # Fallback to top-level title/name — handle rich text list format
    raw_title = item.get("title", item.get("name", "Untitled"))
    if isinstance(raw_title, list) and raw_title:
        # Rich text objects: [{"type": "text", "text": {"content": "..."}, ...}]
        parts = []
        for block in raw_title:
            if isinstance(block, dict):
                parts.append(
                    block.get("plain_text", "")
                    or block.get("text", {}).get("content", "")
                )
        return "".join(parts) or "Untitled"
    if isinstance(raw_title, str):
        return raw_title
    return "Untitled"


def _extract_url(item: dict) -> str:
    """Extract URL from a Notion search result."""
    return item.get("url", item.get("public_url", ""))


def _page_id_from_url(url: str) -> str:
    """Extract page ID from a Notion URL.

    Notion URLs look like: https://www.notion.so/workspace/Page-Title-abc123def456
    The last 32 chars (without hyphens) are the page ID.
    """
    # Strip query params
    clean = url.split("?")[0].rstrip("/")

    # Get last path segment
    last_segment = clean.split("/")[-1]

    # The page ID is the last 32 hex chars (possibly with hyphens)
    # It can be at the end of the slug: "Page-Title-abc123def456"
    # Or it can be the whole segment if it's just an ID
    hex_chars = "".join(c for c in last_segment if c in "0123456789abcdef")

    if len(hex_chars) >= 32:
        raw_id = hex_chars[-32:]
        # Format as UUID
        return f"{raw_id[:8]}-{raw_id[8:12]}-{raw_id[12:16]}-{raw_id[16:20]}-{raw_id[20:]}"

    return last_segment
